import Navbar from '@/components/Navbar';
import Provider from '@/components/Provider';
import { Toaster } from '@/components/ui/Toast';
import { cn } from '@/lib/utils';
import '@/styles/globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,}: {children: React.ReactNode}) {





  return (
    <html
    lang='en'
    className={cn('bg-white text-slate-900 antialiased', inter.className)}>
    <body className='min-h-screen bg-slate-50 dark:bg-slate-900 antialiased'>
      <Provider>
        {/* @ts-expect-error Server Component */}
        <Navbar />
         <Toaster position='bottom-right' />

        {/* <MobileMenu /> */}

        <main>{children}</main>
      </Provider>

      {/* Allow more height for mobile menu on mobile */}
      <div className='h-40 md:hidden' />
    </body>
  </html>
  )
}
